// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get_all_containers() {
  return window['go']['main']['App']['Get_all_containers']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
